# ############################################################################
# Model: Transformer LM of E2E ASR
# Tokens: unigram
# losses: NLL
# Training: AISHELL-1 transcript
# Authors:  YAO-FEI, CHENG 2022
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 2223
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/Transformer_global_epoch_20_h_4_layer_12_lr_10_none_weight_0.1_1.0_start_from_10_m_0.9_no_mask/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
# The data_folder is needed because we train the LM on the training
# transcriptions of AISHELL
data_folder: /mnt/md0/user_jamfly/sb_data/aishell-openslr  # e.g, /path/to/aishell
skip_prep: False
train_data: !ref <output_folder>/train.csv
valid_data: !ref <output_folder>/dev.csv
test_data: !ref <output_folder>/test.csv

# Tokenizer model
tokenizer_file: speechbrain/asr-transformer-aishell/tokenizer.ckpt

# Training parameters
number_of_epochs: 20
batch_size: 128
lr: 10
accu_steps: 1 # Gradient accumulation to simulate large batch training
ckpt_interval_minutes: 15 # save checkpoint every N min
sorting: random

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True
    pin_memory: True
    num_workers: 32

valid_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1

# Outputs
output_neurons: 5000
blank_index: 0
bos_index: 1
eos_index: 2
unk_index: 0
pad_index: 0

# model params
d_model: 512


# Functions
model: !new:speechbrain.lobes.models.transformer.TransformerLM.GlobalTransformerLM # yamllint disable-line rule:line-length
    vocab: !ref <output_neurons>
    d_model: !ref <d_model>
    nhead: 4
    num_encoder_layers: 12
    num_decoder_layers: 0
    d_ffn: 2048
    dropout: 0
    activation: !name:torch.nn.GELU
    normalize_before: False
    query_vocab_size: !ref <output_neurons>
    key_vocab_size: !ref <output_neurons>
    global_momentum: 0.9
    is_mask_diagonal: False
    #global_pooling: mean # sum

first_stage: 10
global_weight_scheduler: !new:speechbrain.nnet.schedulers.LinearScheduler
    initial_value: 0.1
    final_value: 1.0
    epoch_count: !ref <first_stage>

modules:
    model: !ref <model>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

optimizer: !name:torch.optim.Adam
    lr: 0
    betas: (0.9, 0.98)
    eps: 0.000000001

lr_annealing: !new:speechbrain.nnet.schedulers.NoamScheduler
    lr_initial: !ref <lr>
    n_warmup_steps: 250000
    model_size: !ref <d_model>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_cost: !name:speechbrain.nnet.losses.nll_loss

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

tokenizer: !new:sentencepiece.SentencePieceProcessor

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        tokenizer: !ref <tokenizer>
    paths:
        tokenizer: !ref <tokenizer_file>
