# ################################
# Model: SepFormer for source separation
# https://arxiv.org/abs/2010.13154
# Dataset : WSJ0-2mix and WSJ0-3mix
# ################################
# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
#
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data params

# e.g. '/yourpath/wsj0-mix/2speakers'
# end with 2speakers for wsj0-2mix or 3speakers for wsj0-3mix
data_folder: /mnt/md0/user_fal1210/corpora_135/TAT-mix

# the path for wsj0/si_tr_s/ folder -- only needed if dynamic mixing is used
# e.g. /yourpath/wsj0-processed/si_tr_s/
base_folder_dm: /yourpath/wsj0-processed/si_tr_s/

experiment_name: dprnn_android_train_random
output_folder: !ref results/<experiment_name>/<seed>
train_log: !ref <output_folder>/train_log.txt
save_folder: !ref <output_folder>/save
train_data: !ref <save_folder>/tat_tr.csv
valid_data: !ref <save_folder>/tat_cv.csv
test_data: !ref <save_folder>/tat_tt.csv
skip_prep: False


# Experiment params
auto_mix_prec: False # Set it to True for mixed precision
test_only: False
num_spks: 2 # set to 3 for wsj0-3mix
progressbar: True
save_audio: False # Save estimated sources on disk
sample_rate: 8000
valid_test: False
save_valid_test: valid # valid, test
train_embed: False
use_toy: False

# Channel params
test_channel: android # android, condenser, ios, lavalier, XYH-6-X, XYH-6-Y
use_test_channel: False
loss_kind: snr
loss_weight: 0
chan_id_weight: 0
channel_adapt: True
change_channel: False
change_utt_order: True
random_channel: True
infer_0: False
train_one: False
pretrain: 0 #epochs
emb_dim: 128
use_adain: True
use_affine: True
pre_encoding: encoder # stft, fbank, encoder

# Training parameters
N_epochs: 100  # pretrain + train epoch
batch_size: 4
lr: 0.00015
clip_grad_norm: 5
loss_upper_lim: 999999  # this is the upper limit for an acceptable loss
# if True, the training sequences are cut to a specified length
limit_training_signal_len: True
# this is the length of sequences if we choose to limit
# the signal length of training sequences
training_signal_len: 32000

# Set it to True to dynamically create mixtures at training time
dynamic_mixing: False

# Parameters for data augmentation
use_wavedrop: False
use_speedperturb: True
use_speedperturb_sameforeachsource: False
use_rand_shift: False
min_shift: -8000
max_shift: 8000

speedperturb: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 1.0
    drop_freq_prob: 0.0
    drop_chunk_prob: 0.0
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 0.0
    drop_freq_prob: 1.0
    drop_chunk_prob: 1.0
    sample_rate: !ref <sample_rate>

# loss thresholding -- this thresholds the training loss
threshold_byloss: True
threshold: -30

# Encoder parameters
N_encoder_out: 256
out_channels: 256
kernel_size: 16
kernel_stride: 8

# Dataloader options
dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: 3

testloader_opts:
    batch_size: 1
    num_workers: 3

embedloader_opts:
    batch_size: 256
    num_workers: 3

# Specifying the network
Encoder: !new:speechbrain.lobes.models.channel_adapt.Encoder
    kernel_size: !ref <kernel_size>
    out_channels: !ref <N_encoder_out>


intra: !new:speechbrain.lobes.models.channel_adapt.SBRNNBlock
    num_layers: 1
    input_size: !ref <out_channels>
    hidden_channels: !ref <out_channels>
    dropout: 0
    bidirectional: True

inter: !new:speechbrain.lobes.models.channel_adapt.SBRNNBlock
    num_layers: 1
    input_size: !ref <out_channels>
    hidden_channels: !ref <out_channels>
    dropout: 0
    bidirectional: True

pre_MaskNet: !new:speechbrain.lobes.models.channel_adapt.Dual_Path_Model_pre
    num_spks: !ref <num_spks>
    in_channels: !ref <N_encoder_out>
    out_channels: !ref <out_channels>
    num_layers: 6
    K: 250
    intra_model: !ref <intra>
    inter_model: !ref <inter>
    norm: ln
    linear_layer_after_inter_intra: True
    skip_around_intra: True
    dim_cond: !ref <emb_dim>
    use_adain: !ref <use_adain>
    use_affine: !ref <use_affine>

post_MaskNet: !new:speechbrain.lobes.models.channel_adapt.Dual_Path_Model_post
    num_spks: !ref <num_spks>
    in_channels: !ref <N_encoder_out>
    out_channels: !ref <out_channels>

post_MaskNet_channel: !new:speechbrain.lobes.models.channel_adapt.Dual_Path_Model_post
    num_spks: 1
    in_channels: !ref <N_encoder_out>
    out_channels: !ref <out_channels>

Decoder_channel: !new:speechbrain.lobes.models.channel_adapt.Decoder
    in_channels: !ref <N_encoder_out>
    out_channels: 1
    kernel_size: !ref <kernel_size>
    stride: !ref <kernel_stride>
    bias: False

Decoder: !new:speechbrain.lobes.models.channel_adapt.Decoder
    in_channels: !ref <N_encoder_out>
    out_channels: 1
    kernel_size: !ref <kernel_size>
    stride: !ref <kernel_stride>
    bias: False

ChannelEncoder: !new:speechbrain.lobes.models.channel_adapt.SpkResNet_SE
    layers: [3, 3, 3, 3]
    num_filters: [32, 64, 128, 256]
    encoder_out: !ref <N_encoder_out>
    z_channels: !ref <emb_dim>
    pre_encoding: !ref <pre_encoding>
    encoder_type: SAP
    pooling_param:
        hidden_dim: null
        attention: False
        statistic: False

ChannelClassifier: !new:speechbrain.lobes.models.channel_adapt.SpkClassifier
    emb_dim: !ref <emb_dim>
    total_spk: 6

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0

loss: !name:speechbrain.nnet.losses.channel_adapt_loss

loss_embed: !name:speechbrain.nnet.losses.embedding_loss

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
    factor: 0.5
    patience: 2
    dont_halve_until_epoch: 85

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

modules:
    encoder: !ref <Encoder>
    decoder: !ref <Decoder>
    pre_masknet: !ref <pre_MaskNet>
    post_masknet: !ref <post_MaskNet>
    post_masknet_channel: !ref <post_MaskNet_channel>
    decoder_channel: !ref <Decoder_channel>
    channelencoder: !ref <ChannelEncoder>
    channelclassifier: !ref <ChannelClassifier>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        encoder: !ref <Encoder>
        decoder: !ref <Decoder>
        pre_masknet: !ref <pre_MaskNet>
        post_masknet: !ref <post_MaskNet>
        post_masknet_channel: !ref <post_MaskNet_channel>
        decoder_channel: !ref <Decoder_channel>
        channelencoder: !ref <ChannelEncoder>
        channelclassifier: !ref <ChannelClassifier>
        counter: !ref <epoch_counter>
        lr_scheduler: !ref <lr_scheduler>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
