# ################################
# Model: SepFormer for source separation
# https://arxiv.org/abs/2010.13154
# Dataset : WSJ0-2mix and WSJ0-3mix
# ################################
# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
#
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data params

# e.g. '/yourpath/wsj0-mix/2speakers'
# end with 2speakers for wsj0-2mix or 3speakers for wsj0-3mix
data_folder: musdb18

# Data restore path
origin_datapath: /mnt/md1/datasets/musdb18
target_datapath: musdb18

# experiment_name: demucs_vocals_aug_stride_3_b4_grad_norm
experiment_name: demucs
output_folder: !ref results/<experiment_name>/<seed>
train_log: !ref <output_folder>/train_log.txt
save_folder: !ref <output_folder>/save
save_results: !ref <output_folder>/separated_results
train_data: !ref <save_folder>/musdb18_train.csv
valid_data: !ref <save_folder>/musdb18_valid.csv
test_data: !ref <save_folder>/musdb18_test.csv
nomalize_data: !ref /mnt/md1/user_victor/speechbrain/recipes/MUSDB18/meta/musdb.json
skip_prep: False

# Experiment params
test_only: False
num_sources: 4
progressbar: True
sample_rate: 44100
samples: 441000
data_stride: 44100 # samples

# Training parameters
grad_accum_count: 21
N_epochs: 500
batch_size: 3
lr: 0.0003
clip_grad_norm: 5
loss_upper_lim: 999999  # this is the upper limit for an acceptable loss
# if True, the training sequences are cut to a specified length
limit_training_signal_len: False
# this is the length of sequences if we choose to limit
# the signal length of training sequences
training_signal_len: 132300 # sample rate 44100 * 3
# valid_signal_len: 1764000 # sample rate 44100 * 40

# train_seg_dur: !ref <samples> # train seg length (sec)
# valid_seg_dur: !ref <samples> # valid seg length (sec)
split: True # apply model params

# Group Remix
remix_group_size: 1

# Dataloader options
source_names: ["vocals", "bass", "drums", "other"]
# source_names: ["vocals"]
dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: 3

# Specifying the network
model: !new:speechbrain.lobes.models.DEMUCS.Demucs
    sources: !ref <source_names>
    audio_channels: 2
    channels: 64
    depth: 6
    rewrite: True
    glu: True
    rescale: 0.1
    resample: True
    kernel_size: 8
    stride: 4
    growth: 2.0
    lstm_layers: 2
    context: 3
    normalize: False
    samplerate: 44100
    segment_length: 441000

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>

loss: !name:speechbrain.nnet.losses.l1_loss

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
    factor: 0.5
    patience: 10

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

modules:
    module: !ref <model>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        module: !ref <model>
        counter: !ref <epoch_counter>
        lr_scheduler: !ref <lr_scheduler>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
