# ################################
# Model: SepFormer for source separation
# https://arxiv.org/abs/2010.13154
# Dataset : MUSDB18
# ################################
# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
#
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data params

# e.g. '/yourpath/wsj0-mix/2speakers'
data_folder: musdb18

# Data restore path
origin_datapath: /mnt/md1/datasets/musdb18
target_datapath: musdb18

experiment_name: swave
output_folder: !ref results/<experiment_name>/<seed>
train_log: !ref <output_folder>/train_log.txt
save_folder: !ref <output_folder>/save
save_results: !ref <output_folder>/separated_results
train_data: !ref <save_folder>/musdb18_train.csv
valid_data: !ref <save_folder>/musdb18_valid.csv
test_data: !ref <save_folder>/musdb18_test.csv
skip_prep: False


# Experiment params
auto_mix_prec: False # Set it to True for mixed precision
test_only: False
num_sources: 4
progressbar: True
sample_rate: 44100
samples: 132300
data_stride: 132300 # samples
inference_segment_length: 441000 # Inference windowing segment length
split: True # apply model params
no_pad: True # No padding when applying model

# Training parameters
grad_accum_count: 4
N_epochs: 200
batch_size: 1
lr: 0.00025
clip_grad_norm: 5
loss_upper_lim: 999999  # this is the upper limit for an acceptable loss

# Set it to True to dynamically create mixtures at training time
dynamic_mixing: False

# Parameters for data augmentation
use_wavedrop: False
use_speedperturb: True
use_speedperturb_sameforeachsource: False
use_rand_shift: False
min_shift: -8000
max_shift: 8000

speedperturb: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 1.0
    drop_freq_prob: 0.0
    drop_chunk_prob: 0.0
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 0.0
    drop_freq_prob: 1.0
    drop_chunk_prob: 1.0
    sample_rate: !ref <sample_rate>

# loss thresholding -- this thresholds the training loss
threshold_byloss: True
threshold: -30

# Dataloader options
source_names: ["vocals", "bass", "drums", "other"]
dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: 3

# Swave
model: !new:speechbrain.lobes.models.swave.SWave
    sources: !ref <source_names>
    N: 128                              # Convolution Layer
    L: 14                               # Kernel Size
    H: 128                              # LSTM Neurons
    R: 6                                # MULCAT Blocks (output layers)
    C: !ref <num_sources>               # Number Sources
    samplerate: !ref <sample_rate>      # Sample Rate
    segment: 4                          # Chunk Size
    input_normalize: False
    segment_length: !ref <inference_segment_length> # Inference windowing segment length

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>

loss: !name:speechbrain.nnet.losses.l1_loss

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
    factor: 0.3
    patience: 500

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

modules:
    module: !ref <model>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        module: !ref <model>
        counter: !ref <epoch_counter>
        lr_scheduler: !ref <lr_scheduler>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
